# Generated by Django 4.0.4 on 2022-04-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='none', max_length=256)),
                ('slug', models.CharField(default='none', max_length=256)),
                ('content', models.TextField(null=True)),
                ('tag', models.CharField(max_length=128, null=True)),
                ('source', models.CharField(default='none', max_length=128)),
                ('date', models.DateField(null=True)),
                ('images', models.TextField(default='none')),
            ],
            options={
                'db_table': 'articles',
                'ordering': ['source'],
            },
        ),
    ]
